name: auth
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  logger: ^1.1.0
  logging: ^1.1.0
  sizer: ^2.0.15
  hexcolor: ^2.0.7
  image_picker: ^0.8.6
  lottie: ^1.4.0
  path_provider: ^2.0.12
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  otp_text_field: ^1.1.3
  package_info_plus: ^3.0.1
  #  camera: ^0.8.1+7
  flutter_image_compress: ^1.1.3
  permission_handler: 10.0.0
  flutter_svg: ^1.1.1+1

  intl: ^0.17.0

  easy_debounce: ^2.0.3
  file_picker: ^5.2.10

  cloud_firestore: 4.4.5
  firebase_storage: ^11.2.5
  #  cron: ^0.5.1

  # location
  dio: ^5.0.0


  #qr scanner
  #  mobile_scanner: ^3.0.0

  #vibrate
  vibration: ^1.7.6
  #autofillotp
  sms_autofill: ^2.3.0


  #  #flashlight
  #  torch_light: ^1.0.0

  #firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_messaging: ^14.2.4
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.otf
        - asset: assets/fonts/PoppinsMedium.otf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.otf
          weight: 600
        - asset: assets/fonts/PoppinsBold.otf
          weight: 700


