/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String ic_google = "assets/ic_google.png";
  static const String ic_setting = "assets/images/ic_setting.png";
  static const String icHome = "assets/images/icHome.png";
  static const String icMenu = "assets/images/icMenu.png";
  static const String iconSearch = "assets/images/iconSearch.png";
  static const String inn = "assets/flags/inn.svg";
  static const String map_style = "assets/map_style.json";
  static const String MontserratMedium = "assets/fonts/MontserratMedium.ttf";
  static const String PoppinsBold = "assets/fonts/PoppinsBold.otf";
  static const String PoppinsMedium = "assets/fonts/PoppinsMedium.otf";
  static const String PoppinsRegular = "assets/fonts/PoppinsRegular.otf";
  static const String PoppinsSemiBold = "assets/fonts/PoppinsSemiBold.otf";
  static const String sn = "assets/flags/sn.svg";
}
