/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String flag = "assets/images/flag.png";
  static const String home_ic = "assets/images/home_ic.png";
  static const String homes = "assets/images/homes.png";
  static const String ic_about = "assets/images/ic_about.png";
  static const String ic_calander = "assets/images/ic_calander.png";
  static const String ic_file = "assets/images/ic_file.png";
  static const String ic_heart_red = "assets/images/ic_heart_red.png";
  static const String ic_like = "assets/images/ic_like.png";
  static const String ic_office = "assets/images/ic_office.png";
  static const String ic_percentage = "assets/images/ic_percentage.png";
  static const String ic_profile_black = "assets/images/ic_profile_black.png";
  static const String ic_pulse = "assets/images/ic_pulse.png";
  static const String ic_report = "assets/images/ic_report.png";
  static const String ic_right_arrow = "assets/images/ic_right_arrow.png";
  static const String ic_select = "assets/images/ic_select.png";
  static const String ic_setting = "assets/images/ic_setting.png";
  static const String ic_start_location = "assets/images/ic_start_location.png";
  static const String iconSearch = "assets/images/iconSearch.png";
  static const String icselect = "assets/images/icselect.png";
  static const String icunselect = "assets/images/icunselect.png";
  static const String inn = "assets/flags/inn.svg";
  static const String like = "assets/images/like.png";
  static const String location = "assets/images/location.png";
  static const String logout = "assets/images/logout.png";
  static const String map_style = "assets/map_style.json";
  static const String MontserratMedium = "assets/fonts/MontserratMedium.ttf";
  static const String notifications = "assets/images/notifications.png";
  static const String PoppinsBold = "assets/fonts/PoppinsBold.otf";
  static const String PoppinsMedium = "assets/fonts/PoppinsMedium.otf";
  static const String PoppinsRegular = "assets/fonts/PoppinsRegular.otf";
  static const String PoppinsSemiBold = "assets/fonts/PoppinsSemiBold.otf";
  static const String report = "assets/images/report.png";
  static const String sn = "assets/flags/sn.svg";
  static const String unlike = "assets/images/unlike.png";
}
